### ISSUE TITLE
置顶贴不置顶？

### ISSUE THREAD

**Issue by Clect** [CNUER/core#4]
![](http://www.clect.cn/cnubug/01.jpg)

**Comment by melancn** [comment]
未读的优先。你刷新就好了

**Comment by nroskill** [comment]
这是个feature，置顶仅对板块内有效，对全局TL无效

**Comment by Gizeta** [comment]
我觉得可以改core代码支持全局TL，如果需要讨论的话再reopen

**Comment by nroskill** [comment]
@Gizeta 我觉得这个feature没必要，以后招生的时候，各个院一个院来一个置顶，全局TL炸了

**Comment by AtarisMio** [comment]
@nroskill 可以单独做一个开关。管理全局的。超管权限之类的
